### ISSUE TITLE
Some suggestions to make sx05re more stable and robust.

### ISSUE THREAD

**Issue by SumavisionQ5** [shantigilbert/LibreELEC.tv#69]
By using your fantastic build, I found some problems and I think I can offer some suggestions to make it better.
1. EmulationStation was originally designed for Raspberry which uses Raspbian as its system. Raspbian is different from LibereELEC. The filesystem of Raspbian is editable while LibereELEC's is read-only. This causes a problem: the font of system for LibereELEC is small and lacks many languages' letters and characters. For instance, many games use French letters and Japanese Kanji (character) in their names and description. Due to the absence of font, these French letters and Japanese Kanji would not showed. And to make it worse, if your gamelist is long (for example, 600 games in one gamelist) and you scroll down or up the gamelist too fast, EmulationStaion would freeze and crash. This would produce a lot of garbage cache files. To solve it, I advise you to include a full and complete fonts in the filesystem of LibreELEC before you pack the build. There are many free, I mean copyright-issue-free, in the internet. Fonts-droid is a free one, maybe you can add it to your next build(1.7).
2. The default resolution for SX05RE is 1080p60hz. If we don't set the resoution to 1080p in the Android before we start the SX05RE, the screen would get messy. To avoid it, we can force it to 1080p when system starts up. To do it, we can open \Root\storage\.config\autostart.sh, and add the following lines : 
MODE=`cat /sys/class/display/mode`;
if [ "$MODE" = "1080p60hz" ]; then
fbset -fb /dev/fb0 -g 1920 1080 1920 1080 32
else
echo 1080p60hz > /sys/class/display/mode
fbset -fb /dev/fb0 -g 1920 1080 1920 1080 32
fi
This would force it to 1080p if present resolution isn't 1080p60hz. I open these lines can be added to your build later.
3. Have you considered writing a doc for SX05RE like Lakka and Retropie have done? Maybe you can set a page to offer some FAQs and TIPs for noob. That would helps a lot.
Those are all my suggestions, hope them to make your build more stable and bug-free. Thanks for your hard working, and sorry for your damaged Laptop. Wish you can be back soon.

**Comment by shantigilbert** [comment]
Thanks I am open to pull requests on all of those suggestions, especially 1 and 2, if you have made and test the changes submit them and I will approve them.

I have not though of writing a doc, since this started as a personal project something I could use on my own, and I thought people could also enjoy, but I am just one guy that knew nothing about LibreElec and started from scratch, I have a regular job and I only work on this on my spare time, for free. I honestly doubt I could have time to write a doc. Most of the FAQ's that work on Lakka and LE will also most likely work here. 

Again if you or anyone else want to contribute and help make this a better build, I am more than open :)
