### ISSUE TITLE
Need help on Nanopi-K2

### ISSUE THREAD

**Issue by WXDFever** [shantigilbert/LibreELEC.tv#70]
Hello, Buddy. Sorry to bother you, so here is the thing: My friend got a Nanopi-K2(s905), he was wondering if he can use sx05re on this device, so he tried it with a tf card to boot and it fails. Can you help us to look into this? Here is the wiki link for this board:
http://wiki.friendlyarm.com/wiki/index.php/NanoPi_K2

**Comment by shantigilbert** [comment]
I would be almost impossible to know why its not working without a unit in hand or at least some error information. when you say it fails, does it give you an error? or anything on the screen for that matter?

**Comment by WXDFever** [comment]
Hello, Thanks for you reply. There is no error message, just a black  screen. I was wondering so sx05re needs the uboot to launch, right? My s905 mxq boxes works fine because the android has the uboot? BTW, My friend tried with lakka (Odroid-C2 version: http://www.lakka.tv/get/linux/odroidc2/) and it works fine, but we don't like lakka, we love sx05re, is there any way we can launch sx05re on this Nanopi-K2? 

Thanks again for your help and support

**Comment by shantigilbert** [comment]
Libreelec supports Odroid c2 as well so I guess it could work, changes would need to be made so that when you compile it for the Odroid C2 it adds the Sx05RE. I do not own any of those boards so it would be impossible for me to test, but I could probably make the changes so that it compiles for Odroid C2

**Comment by WXDFever** [comment]
Alright, thanks for your help and reply. Sorry for bringing up so much trouble to you

**Comment by shantigilbert** [comment]
I tried compiling for the Odroid C2, but it seems the version I use for LibreElec only supports 64bit arch, so some emulators might not work as intended. I will upload a binary later. 

I see Lakka made the Odroid c3 work on 32bits, so I am looking at their code and see if I can figure it out, but I won't promise anything since it will be imposible for me to test.

**Comment by shantigilbert** [comment]
@WXDFever unfortunately it seems this is something that might be out of my league. Can't get it to compile at allá for odroid in ARM. I will keep trying but no promises

**Comment by WXDFever** [comment]
@shantigilbert That's totally fine! Keep up the good work,lol
